more robust __new__ override. Better py2.x compatibility.
I must admit I haven't yet figured out this issue completely.
This, however, could be a good trail to follow to further, pending
investigation.
http://stackoverflow.com/questions/9100409/using-new-on-classes-derived-from-djangos-models-does-not-work

Without this change, on py2.7 we get a weird error when using
the singleton decorator on pyrana/ff.py:

c1 = Klass()
TypeError: unbound method singleton_new() must be called with Klass instance as first argument (got type instance instead)

where Klass is just a braindead

class Klass(object):
    pass

A single hint led me to this change (and to think I'm on the right track):
singleton_new() in the singleton decorator is wrongly seen as unbound method,
not like a static method. So, re-stating it as staticmethod should improve the issue.
Looks like this actually fix the problem!

But what still puzzles me is that I don't yet fully understand the bug itself because,
unlike any other related scenario I found so far, metaclasses are *not* involved here.
And I fail to see why this doesn't show up in python 3.x: a quick changelog scan
brings no relevant changes.